'use strict';function z(h,a,b,e){h.s.sc(h.Za,a,b,e,void 0)}function H(h,a,b,e){h.s.ca?z(h,a,b,e):h.s.rf()._OnMessageFromDOM({type:"event",component:h.Za,handler:a,dispatchOpts:e||null,data:b,responseId:null})}function J(h,a,b){h.s.C(h.Za,a,b)}function L(h,a){for(const [b,e]of a)J(h,b,e)}function M(h){h.Rb||(h.s.$e(h.ie),h.Rb=!0)}window.wb=class{constructor(h,a){this.s=h;this.Za=a;this.Rb=!1;this.ie=()=>this.Ca()}jd(){}Ca(){}};function N(h){-1!==h.Pa&&(self.clearTimeout(h.Pa),h.Pa=-1)}
window.Qe=class{constructor(h,a){this.Pc=h;this.Jg=a;this.Pa=-1;this.Sb=-Infinity;this.je=()=>{this.Pa=-1;this.Sb=Date.now();this.eb=!0;this.Pc();this.eb=!1};this.Pd=this.eb=!1}f(){N(this);this.je=this.Pc=null}};"use strict";function O(h,a){J(h,"get-element",b=>{const e=h.ba.get(b.elementId);return a(e,b)})}
window.eh=class extends self.wb{constructor(h,a){super(h,a);this.ba=new Map;this.Oc=!0;L(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const e=this.ba.get(b);this.Oc&&e.parentElement.removeChild(e);this.ba.delete(b)}}],["set-visible",b=>{this.Oc&&(this.ba.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Oc){var e=this.ba.get(b.elementId);e.style.left=b.left+"px";e.style.top=b.top+"px";e.style.width=b.width+"px";e.style.height=
b.height+"px";b=b.fontSize;null!==b&&(e.style.fontSize=b+"em")}}],["update-state",b=>{this.ba.get(b.elementId);throw Error("required override");}],["focus",b=>{{const e=this.ba.get(b.elementId);b.focus?e.focus():e.blur()}}],["set-css-style",b=>{this.ba.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ba.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ba.get(b.elementId).removeAttribute(b.name)}]]);O(this,b=>b)}};"use strict";
{const h=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),a=/android/i.test(navigator.userAgent);let b=0;function e(m){const c=document.createElement("script");c.async=!1;c.type="module";return m.Ug?new Promise(k=>{const l="c3_resolve_"+b;++b;self[l]=k;c.textContent=m.Yg+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=m;document.head.appendChild(c)})}let g=!1,n=!1;function q(){if(!g){try{new Worker("blob://",{get type(){n=
!0}})}catch(m){}g=!0}return n}let v=new Audio;const B={"audio/webm; codecs=opus":!!v.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!v.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!v.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!v.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!v.canPlayType("audio/mp4"),"audio/mpeg":!!v.canPlayType("audio/mpeg")};v=null;async function D(m){m=await w(m);return(new TextDecoder("utf-8")).decode(m)}
function w(m){return new Promise((c,k)=>{const l=new FileReader;l.onload=p=>c(p.target.result);l.onerror=p=>k(p);l.readAsArrayBuffer(m)})}const x=[];let C=0;window.RealFile=window.File;const E=[],A=new Map,F=new Map;let I=0;const K=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");K.push(m)};const d=new Set(["cordova","playable-ad","instant-games"]);let f=!1;window.Bb=class m{constructor(c){this.ca=c.$g;this.qa=null;this.F="";this.ec=c.Xg;
this.ub={};this.Ia=this.tb=null;this.Pb=[];this.G=this.Na=null;this.Vd=!1;this.hb=null;this.Ma=-1;this.Og=()=>this.Sf();this.La=[];this.v=c.ke;this.fb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&q()||(this.ca=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ca=!1;if("cordova"===this.v&&this.ca)if(a){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.ca=!1)}else this.ca=!1;this.Vb=this.ia=
null;"html5"!==this.v&&"playable-ad"!==this.v||!this.fb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.v||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",k=>this.Af(k));
this.C("runtime","create-job-worker",()=>this.Bf());"cordova"===this.v?document.addEventListener("deviceready",()=>this.Bd(c)):this.Bd(c)}f(){this.yc();this.qa&&(this.qa=this.qa.onmessage=null);this.tb&&(this.tb.terminate(),this.tb=null);this.Ia&&(this.Ia.f(),this.Ia=null);this.G&&(this.G.parentElement.removeChild(this.G),this.G=null)}Le(){return h&&"cordova"===this.v}rc(){const c=navigator.userAgent;return h&&d.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}Je(){return a}qd(){return a&&
d.has(this.v)}async Bd(c){"macos-wkwebview"===this.v&&this.kg();if("playable-ad"===this.v){this.ia=self.c3_base64files;this.Vb={};await this.ef();for(let l=0,p=c.Qa.length;l<p;++l){var k=c.Qa[l].toLowerCase();this.Vb.hasOwnProperty(k)?c.Qa[l]={Ug:!0,Yg:this.Vb[k]}:this.ia.hasOwnProperty(k)&&(c.Qa[l]=URL.createObjectURL(this.ia[k]))}}c.Pg?this.F=c.Pg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));c.bh&&(this.ub=
c.bh);k=new MessageChannel;this.qa=k.port1;this.qa.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Of(l));this.hb=new self.Me(this);await P(this.hb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ca?await this.uf(c,k.port2):await this.tf(c,k.port2)}Bc(c){c=this.ub.hasOwnProperty(c)?this.ub[c]:c.endsWith("/workermain.js")&&this.ub.hasOwnProperty("workermain.js")?
this.ub["workermain.js"]:"playable-ad"===this.v&&this.ia.hasOwnProperty(c.toLowerCase())?this.ia[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async lc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.v&&this.fb)return c=await this.vb(l.Tg?c:this.ec+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");
c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}oa(){return Math.max(window.innerWidth,1)}fa(){return Math.max(window.innerHeight,1)}Ad(c){var k=this.hb;return{baseUrl:this.F,previewUrl:location.href,windowInnerWidth:this.oa(),windowInnerHeight:this.fa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:m.Ta(),projectData:c.jh,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,
swClientId:window.hh||"",exportType:c.ke,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.ih,jobScheduler:{inputPort:k.Wc,outputPort:k.bd,maxNumWorkers:k.Lg},supportedAudioFormats:B,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ec+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ec+"opus.wasm.wasm",isFileProtocol:this.fb,isiOSCordova:this.Le(),isiOSWebView:this.rc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async uf(c,k){var l=this.Bc(c.ah);this.tb=
await this.lc(l,this.F,{type:"module",name:"Runtime",Tg:!0});this.G=document.createElement("canvas");this.G.style.display="none";l=this.G.transferControlToOffscreen();document.body.appendChild(this.G);window.c3canvas=this.G;let p=c.hd||[],u=c.Qa;p=await Promise.all(p.map(r=>this.Da(r)));u=await Promise.all(u.map(r=>this.Da(r)));if("cordova"===this.v)for(let r=0,t=c.ic.length;r<t;++r){const y=c.ic[r],G=y[0];if(G===c.fd||"scriptsInEvents.js"===G||G.endsWith("/scriptsInEvents.js"))y[1]=await this.Da(G)}this.tb.postMessage(Object.assign(this.Ad(c),
{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:p,engineScripts:u,projectScripts:c.ic,mainProjectScript:c.fd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...Q(this.hb)]);this.Pb=E.map(r=>new r(this));this.zd();self.c3_callFunction=(r,t)=>this.Na.vf(r,t);"preview"===this.v&&(self.goToLastErrorScript=()=>this.sc("runtime","go-to-last-error-script"))}async tf(c,k){this.G=document.createElement("canvas");this.G.style.display="none";document.body.appendChild(this.G);
window.c3canvas=this.G;this.Pb=E.map(r=>new r(this));this.zd();var l=c.Qa.map(r=>"string"===typeof r?(new URL(r,this.F)).toString():r);Array.isArray(c.hd)&&l.unshift(...c.hd);l=await Promise.all(l.map(r=>this.Da(r)));await Promise.all(l.map(r=>e(r)));l=self.C3_ProjectScriptsStatus;const p=c.fd,u=c.ic;for(let [r,t]of u)if(t||(t=r),r===p)try{t=await this.Da(t),await e(t),"preview"!==this.v||l[r]||this.Jd(r,"main script did not run to completion")}catch(y){this.Jd(r,y)}else if("scriptsInEvents.js"===
r||r.endsWith("/scriptsInEvents.js"))t=await this.Da(t),await e(t);"preview"===this.v&&"object"!==typeof self.dh.fh?(this.Jb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.Ad(c),{isInWorker:!1,messagePort:k,canvas:this.G,runOnStartupFunctions:K}),this.Dd(),this.Ia=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ia,
c))}Jd(c,k){this.Jb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Dd(){this.Jb()}Jb(){const c=window.Qg;c&&(c.parentElement.removeChild(c),window.Qg=null)}async Bf(){const c=await R(this.hb);return{outputPort:c,transferables:[c]}}rf(){if(this.ca)throw Error("not available in worker mode");return this.Ia}sc(c,k,l,p,u){this.qa.postMessage({type:"event",
component:c,handler:k,dispatchOpts:p||null,data:l,responseId:null},u)}sd(c,k,l,p,u){const r=I++,t=new Promise((y,G)=>{F.set(r,{resolve:y,reject:G})});this.qa.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:r},u);return t}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.Gf(c);if("result"===k)this.Vf(c);else if("runtime-ready"===k)this.Wf();else if("alert-error"===k)this.Jb(),alert(c.message);else if("creating-runtime"===k)this.Dd();else throw Error(`unknown message '${k}'`);
}Gf(c){const k=c.component,l=c.handler,p=c.data,u=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(p)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==u&&this.Ib(u,!1,""+t);return}if(null===u)return r;r&&r.then?r.then(t=>this.Ib(u,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Ib(u,!1,""+t)}):this.Ib(u,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Ib(c,
k,l){let p;l&&l.transferables&&(p=l.transferables);this.qa.postMessage({type:"result",responseId:c,isOk:k,result:l},p)}Vf(c){const k=c.responseId,l=c.isOk;c=c.result;const p=F.get(k);l?p.resolve(c):p.reject(c);F.delete(k)}C(c,k,l){let p=A.get(c);p||(p=new Map,A.set(c,p));if(p.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);p.set(k,l)}static jc(c){if(E.includes(c))throw Error("DOM handler already added");E.push(c)}zd(){for(const c of this.Pb)if("runtime"===c.Za){this.Na=c;return}throw Error("cannot find runtime DOM handler");
}Of(c){this.sc("debugger","message",c)}Wf(){for(const c of this.Pb)c.jd()}static Ta(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||f)}static Kd(c){f=!!c}$e(c){this.La.push(c);this.Mc()}hg(c){c=this.La.indexOf(c);if(-1===c)throw Error("invalid callback");this.La.splice(c,1);this.La.length||this.yc()}Mc(){-1===this.Ma&&this.La.length&&(this.Ma=requestAnimationFrame(this.Og))}yc(){-1!==this.Ma&&(cancelAnimationFrame(this.Ma),this.Ma=-1)}Sf(){this.Ma=
-1;for(const c of this.La)c();this.Mc()}va(c){this.Na.va(c)}Ba(c){this.Na.Ba(c)}Lc(){this.Na.Lc()}Db(c){this.Na.Db(c)}Ke(){return!!B["audio/webm; codecs=opus"]}async Hg(c){c=await this.sd("runtime","opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}Te(){this.Vd=!0}Ie(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}rd(c){return!this.Ie(c)}async Da(c){return"cordova"===this.v&&(c.startsWith("file:")||this.fb&&this.rd(c))?(c.startsWith(this.F)&&
(c=c.substr(this.F.length)),c=await this.vb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async Af(c){const k=c.filename;switch(c.as){case "text":return await this.Be(k);case "buffer":return await this.vb(k);default:throw Error("unsupported type");}}md(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,p)=>{window.resolveLocalFileSystemURL(k,u=>{u.file(l,p)},p)})}async Be(c){c=await this.md(c);return await D(c)}zc(){if(x.length&&
!(8<=C)){C++;var c=x.shift();this.ff(c.filename,c.Zg,c.Sg)}}vb(c){return new Promise((k,l)=>{x.push({filename:c,Zg:p=>{C--;this.zc();k(p)},Sg:p=>{C--;this.zc();l(p)}});this.zc()})}async ff(c,k,l){try{const p=await this.md(c),u=await w(p);k(u)}catch(p){l(p)}}kg(){var c={type:"ready"};if("windows-webview2"===this.v)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.v)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");
}async ef(){const c=[];for(const [k,l]of Object.entries(this.ia))c.push(this.df(k,l));await Promise.all(c)}async df(c,k){if("object"===typeof k)this.ia[c]=new Blob([k.str],{type:k.type}),this.Vb[c]=k.str;else{let l=await this.pf(k);l||(l=this.hf(k));this.ia[c]=l}}async pf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}hf(c){c=this.bg(c);return this.cf(c.data,c.Vg)}bg(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||"";const p=k[2];l="base64"===k[1]||"base64"===p?atob(l):decodeURIComponent(l);return{Vg:c,data:l}}cf(c,k){var l=c.length;let p=l>>2,u=new Uint8Array(l),r=new Uint32Array(u.buffer,0,p),t,y;for(y=t=0;t<p;++t)r[t]=c.charCodeAt(y++)|c.charCodeAt(y++)<<8|c.charCodeAt(y++)<<16|c.charCodeAt(y++)<<24;for(l&=
3;l--;)u[y]=c.charCodeAt(y),++y;return new Blob([u],{type:k})}}}"use strict";
{const h=self.Bb;function a(d){return d.sourceCapabilities&&d.sourceCapabilities.firesTouchEvents||d.originalEvent&&d.originalEvent.sourceCapabilities&&d.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),e={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(d){return new Promise((f,m)=>{const c=document.createElement("link");c.onload=()=>f(c);c.onerror=k=>m(k);c.rel=
"stylesheet";c.href=d;document.head.appendChild(c)})}function v(d){return new Promise((f,m)=>{const c=new Image;c.onload=()=>f(c);c.onerror=k=>m(k);c.src=d})}async function B(d){d=URL.createObjectURL(d);try{return await v(d)}finally{URL.revokeObjectURL(d)}}function D(d){return new Promise((f,m)=>{let c=new FileReader;c.onload=k=>f(k.target.result);c.onerror=k=>m(k);c.readAsText(d)})}async function w(d,f,m){if(!/firefox/i.test(navigator.userAgent))return await B(d);var c=await D(d);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),p=k.getAttribute("height");if(!l.includes("%")&&!p.includes("%"))return await B(d)}k.setAttribute("width",f+"px");k.setAttribute("height",m+"px");c=(new XMLSerializer).serializeToString(c);d=new Blob([c],{type:"image/svg+xml"});return await B(d)}function x(d){do{if(d.parentNode&&d.hasAttribute("contenteditable"))return!0;d=d.parentNode}while(d);return!1}const C=new Set(["input",
"textarea","datalist","select"]),E=new Set(["canvas","body","html"]);function A(d){E.has(d.target.tagName.toLowerCase())&&d.preventDefault()}function F(d){(d.metaKey||d.ctrlKey)&&d.preventDefault()}self.C3_GetSvgImageSize=async function(d){d=await B(d);if(0<d.width&&0<d.height)return[d.width,d.height];{d.style.position="absolute";d.style.left="0px";d.style.top="0px";d.style.visibility="hidden";document.body.appendChild(d);const f=d.getBoundingClientRect();document.body.removeChild(d);return[f.width,
f.height]}};self.C3_RasterSvgImageBlob=async function(d,f,m,c,k){d=await w(d,f,m);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(d,0,0,f,m);return l};let I=!1;document.addEventListener("pause",()=>I=!0);document.addEventListener("resume",()=>I=!1);function K(){try{return window.parent&&window.parent.document.hasFocus()}catch(d){return!1}}h.jc(class extends self.wb{constructor(d){super(d,"runtime");this.Wd=!0;this.Oa=-1;this.dd="any";this.Ld=this.Md=!1;this.xa=
null;this.Rd="";this.Sc=-1;this.Ha=this.pb=null;this.ac=this.$b=0;this.$d=d.oa();this.Tb=d.fa();this.rb=0;d.C("canvas","update-size",c=>this.Zf(c));d.C("runtime","invoke-download",c=>this.Mf(c));d.C("runtime","raster-svg-image",c=>this.Tf(c));d.C("runtime","get-svg-image-size",c=>this.Kf(c));d.C("runtime","set-target-orientation",c=>this.Xf(c));d.C("runtime","register-sw",()=>this.Uf());d.C("runtime","post-to-debugger",c=>this.Fd(c));d.C("runtime","go-to-script",c=>this.Fd(c));d.C("runtime","before-start-ticking",
()=>this.zf());d.C("runtime","debug-highlight",c=>this.Cf(c));d.C("runtime","enable-device-orientation",()=>this.bf());d.C("runtime","enable-device-motion",()=>this.af());d.C("runtime","add-stylesheet",c=>this.xf(c));d.C("runtime","alert",c=>this.yf(c));d.C("runtime","hide-cordova-splash",()=>this.Lf());d.C("runtime","set-exporting-to-video",c=>this.og(c));d.C("runtime","export-to-video-progress",c=>this.Hf(c));d.C("runtime","exported-to-video",c=>this.If(c));const f=new Set(["input","textarea","datalist"]);
window.addEventListener("contextmenu",c=>{const k=c.target;f.has(k.tagName.toLowerCase())||x(k)||c.preventDefault()});const m=d.G;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);m.addEventListener("selectstart",A);m.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),m.addEventListener("pointerdown",A)):m.addEventListener("touchstart",A);this.mb=
0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",F,{passive:!1});window.addEventListener("wheel",F,{passive:!1});window.addEventListener("resize",()=>this.$f());window.addEventListener("fullscreenchange",()=>this.Va());window.addEventListener("webkitfullscreenchange",()=>this.Va());window.addEventListener("mozfullscreenchange",()=>this.Va());window.addEventListener("fullscreenerror",c=>this.Hc(c));window.addEventListener("webkitfullscreenerror",
c=>this.Hc(c));window.addEventListener("mozfullscreenerror",c=>this.Hc(c));if(d.rc())if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const k=window.visualViewport.height;k>c&&(document.scrollingElement.scrollTop=0);c=k})}else window.addEventListener("focusout",()=>{{const l=document.activeElement;if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||
"text"):x(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.ag(c);this.Ja=new Set;this.Wb=new WeakSet;this.pa=!1}zf(){"cordova"===this.s.v?(document.addEventListener("pause",()=>this.Kc(!0)),document.addEventListener("resume",()=>this.Kc(!1))):document.addEventListener("visibilitychange",()=>this.Kc(document.hidden));return{isSuspended:!(!document.hidden&&!I)}}jd(){window.addEventListener("focus",()=>this.Xa("window-focus"));window.addEventListener("blur",()=>
{this.Xa("window-blur",{parentHasFocus:K()});this.mb=0});window.addEventListener("focusin",f=>{f=f.target;(C.has(f.tagName.toLowerCase())||x(f))&&this.Xa("keyboard-blur")});window.addEventListener("keydown",f=>this.Ed("keydown",f));window.addEventListener("keyup",f=>this.Ed("keyup",f));window.addEventListener("dblclick",f=>this.Ic("dblclick",f,e));window.addEventListener("wheel",f=>this.Qf(f));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",f=>{this.Cc(f);this.Wa("pointerdown",
f)}),this.s.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.pb=new self.Qe(()=>this.lf(),5),this.pb.Pd=!0,window.addEventListener("pointerrawupdate",f=>this.Rf(f))):window.addEventListener("pointermove",f=>this.Wa("pointermove",f)),window.addEventListener("pointerup",f=>this.Wa("pointerup",f)),window.addEventListener("pointercancel",f=>this.Wa("pointercancel",f))):(window.addEventListener("mousedown",f=>{this.Cc(f);this.Jc("pointerdown",f)}),window.addEventListener("mousemove",
f=>this.Jc("pointermove",f)),window.addEventListener("mouseup",f=>this.Jc("pointerup",f)),window.addEventListener("touchstart",f=>{this.Cc(f);this.Hb("pointerdown",f)}),window.addEventListener("touchmove",f=>this.Hb("pointermove",f)),window.addEventListener("touchend",f=>this.Hb("pointerup",f)),window.addEventListener("touchcancel",f=>this.Hb("pointercancel",f)));const d=()=>this.Lc();window.addEventListener("pointerup",d,!0);window.addEventListener("touchend",d,!0);window.addEventListener("click",
d,!0);window.addEventListener("keydown",d,!0);window.addEventListener("gamepadconnected",d,!0);this.s.Je()&&!this.s.qd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this.Fc(this.fa(),navigator.virtualKeyboard.boundingRect.height)}))}Fc(d,f){document.body.style.transform="";if(0<f){var m=document.activeElement;m&&(m=m.getBoundingClientRect(),d=(m.top+m.bottom)/2-(d-f)/2,d>f&&(d=f),0>d&&(d=0),0<d&&(document.body.style.transform=
`translateY(${-d}px)`))}}Xa(d,f){z(this,d,f||null,n)}oa(){return this.s.oa()}fa(){return this.s.fa()}$f(){const d=this.oa(),f=this.fa();if(this.s.qd()){if(this.$d===d&&f<this.Tb){this.rb=this.Tb-f;this.Fc(this.Tb,this.rb);return}0<this.rb&&(this.rb=0,this.Fc(f,this.rb));this.$d=d;this.Tb=f}this.Xa("window-resize",{innerWidth:d,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:h.Ta()});this.s.rc()&&(-1!==this.Oa&&clearTimeout(this.Oa),this.Gd(d,f,0))}ig(d,f,m){-1!==this.Oa&&clearTimeout(this.Oa);
this.Oa=setTimeout(()=>this.Gd(d,f,m),48)}Gd(d,f,m){const c=this.oa(),k=this.fa();this.Oa=-1;c!=d||k!=f?this.Xa("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:h.Ta()}):10>m&&this.ig(c,k,m+1)}Xf(d){this.dd=d.targetOrientation}Dg(){const d=this.dd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(d).catch(f=>console.warn("[Construct 3] Failed to lock orientation: ",f));else try{let f=!1;screen.lockOrientation?f=screen.lockOrientation(d):
screen.webkitLockOrientation?f=screen.webkitLockOrientation(d):screen.mozLockOrientation?f=screen.mozLockOrientation(d):screen.msLockOrientation&&(f=screen.msLockOrientation(d));f||console.warn("[Construct 3] Failed to lock orientation")}catch(f){console.warn("[Construct 3] Failed to lock orientation: ",f)}}Va(){const d=h.Ta();d&&"any"!==this.dd&&this.Dg();z(this,"fullscreenchange",{isFullscreen:d,innerWidth:this.oa(),innerHeight:this.fa()})}Hc(d){console.warn("[Construct 3] Fullscreen request failed: ",
d);z(this,"fullscreenerror",{isFullscreen:h.Ta(),innerWidth:this.oa(),innerHeight:this.fa()})}Kc(d){d?this.s.yc():this.s.Mc();z(this,"visibilitychange",{hidden:d})}Ed(d,f){"Backspace"===f.key&&A(f);const m=b.get(f.code)||f.code;H(this,d,{code:m,key:f.key,which:f.which,repeat:f.repeat,altKey:f.altKey,ctrlKey:f.ctrlKey,metaKey:f.metaKey,shiftKey:f.shiftKey,timeStamp:f.timeStamp},e)}Qf(d){z(this,"wheel",{clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,deltaX:d.deltaX,deltaY:d.deltaY,
deltaZ:d.deltaZ,deltaMode:d.deltaMode,timeStamp:d.timeStamp},e)}Ic(d,f,m){a(f)||H(this,d,{button:f.button,buttons:f.buttons,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,movementX:f.movementX||0,movementY:f.movementY||0,timeStamp:f.timeStamp},m)}Jc(d,f){if(!a(f)){var m=this.mb;"pointerdown"===d&&0!==m?d="pointermove":"pointerup"===d&&0!==f.buttons&&(d="pointermove");H(this,d,{pointerId:1,pointerType:"mouse",button:f.button,buttons:f.buttons,lastButtons:m,clientX:f.clientX,clientY:f.clientY,
pageX:f.pageX,pageY:f.pageY,movementX:f.movementX||0,movementY:f.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:f.timeStamp},e);this.mb=f.buttons;this.Ic(f.type,f,g)}}Wa(d,f){if(this.pb&&"pointermove"!==d){var m=this.pb;m.eb||(N(m),m.Sb=Date.now())}m=0;"mouse"===f.pointerType&&(m=this.mb);H(this,d,{pointerId:f.pointerId,pointerType:f.pointerType,button:f.button,buttons:f.buttons,lastButtons:m,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,
movementX:(f.movementX||0)+this.$b,movementY:(f.movementY||0)+this.ac,width:f.width||0,height:f.height||0,pressure:f.pressure||0,tangentialPressure:f.tangentialPressure||0,tiltX:f.tiltX||0,tiltY:f.tiltY||0,twist:f.twist||0,timeStamp:f.timeStamp},e);this.ac=this.$b=0;"mouse"===f.pointerType&&(m="mousemove","pointerdown"===d?m="mousedown":"pointerup"===d&&(m="mouseup"),this.Ic(m,f,g),this.mb=f.buttons)}Rf(d){this.Ha&&(this.$b+=this.Ha.movementX||0,this.ac+=this.Ha.movementY||0);this.Ha=d;d=this.pb;
if(-1===d.Pa){var f=Date.now(),m=f-d.Sb,c=d.Jg;m>=c&&d.Pd?(d.Sb=f,d.eb=!0,d.Pc(),d.eb=!1):d.Pa=self.setTimeout(d.je,Math.max(c-m,4))}}lf(){this.Wa("pointermove",this.Ha);this.Ha=null}Hb(d,f){for(let m=0,c=f.changedTouches.length;m<c;++m){const k=f.changedTouches[m];H(this,d,{pointerId:k.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,movementX:f.movementX||0,movementY:f.movementY||0,width:2*(k.radiusX||k.webkitRadiusX||
0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:f.timeStamp},e)}}Cc(d){window!==window.top&&window.focus();this.Cd(d.target)&&document.activeElement&&!this.Cd(document.activeElement)&&document.activeElement.blur()}Cd(d){return!d||d===document||d===window||d===document.body||"canvas"===d.tagName.toLowerCase()}bf(){this.Md||(this.Md=!0,window.addEventListener("deviceorientation",d=>this.Ef(d)),window.addEventListener("deviceorientationabsolute",
d=>this.Ff(d)))}af(){this.Ld||(this.Ld=!0,window.addEventListener("devicemotion",d=>this.Df(d)))}Ef(d){z(this,"deviceorientation",{absolute:!!d.absolute,alpha:d.alpha||0,beta:d.beta||0,gamma:d.gamma||0,timeStamp:d.timeStamp,webkitCompassHeading:d.webkitCompassHeading,webkitCompassAccuracy:d.webkitCompassAccuracy},e)}Ff(d){z(this,"deviceorientationabsolute",{absolute:!!d.absolute,alpha:d.alpha||0,beta:d.beta||0,gamma:d.gamma||0,timeStamp:d.timeStamp},e)}Df(d){let f=null;var m=d.acceleration;m&&(f=
{x:m.x||0,y:m.y||0,z:m.z||0});m=null;var c=d.accelerationIncludingGravity;c&&(m={x:c.x||0,y:c.y||0,z:c.z||0});c=null;const k=d.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});z(this,"devicemotion",{acceleration:f,accelerationIncludingGravity:m,rotationRate:c,interval:d.interval,timeStamp:d.timeStamp},e)}Zf(d){var f=this.s;f.Vd||(f=f.G,f.style.width=d.styleWidth+"px",f.style.height=d.styleHeight+"px",f.style.marginLeft=d.marginLeft+"px",f.style.marginTop=d.marginTop+"px",this.Wd&&
(f.style.display="",this.Wd=!1))}Mf(d){const f=d.url;d=d.filename;const m=document.createElement("a"),c=document.body;m.textContent=d;m.href=f;m.download=d;c.appendChild(m);m.click();c.removeChild(m)}async Tf(d){var f=d.imageBitmapOpts;d=await self.C3_RasterSvgImageBlob(d.blob,d.imageWidth,d.imageHeight,d.surfaceWidth,d.surfaceHeight);f=f?await createImageBitmap(d,f):await createImageBitmap(d);return{imageBitmap:f,transferables:[f]}}async Kf(d){return await self.C3_GetSvgImageSize(d.blob)}async xf(d){await q(d.url)}Lc(){var d=
[...this.Ja];this.Ja.clear();if(!this.pa)for(const f of d)(d=f.play())&&d.catch(()=>{this.Wb.has(f)||this.Ja.add(f)})}va(d){if("function"!==typeof d.play)throw Error("missing play function");this.Wb.delete(d);let f;try{f=d.play()}catch(m){this.Ja.add(d);return}f&&f.catch(()=>{this.Wb.has(d)||this.Ja.add(d)})}Ba(d){this.Ja.delete(d);this.Wb.add(d)}Db(d){this.pa=!!d}Lf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Cf(d){if(d.show){this.xa||(this.xa=document.createElement("div"),
this.xa.id="inspectOutline",document.body.appendChild(this.xa));var f=this.xa;f.style.display="";f.style.left=d.left-1+"px";f.style.top=d.top-1+"px";f.style.width=d.width+2+"px";f.style.height=d.height+2+"px";f.textContent=d.name}else this.xa&&(this.xa.style.display="none")}Uf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Fd(d){window.c3_postToMessagePort&&(d.from="runtime",window.c3_postToMessagePort(d))}vf(d,f){return this.s.sd(this.Za,"js-invoke-function",{name:d,params:f},void 0,void 0)}yf(d){alert(d.message)}ag(d){"entered-fullscreen"===
d?(h.Kd(!0),this.Va()):"exited-fullscreen"===d?(h.Kd(!1),this.Va()):console.warn("Unknown wrapper message: ",d)}og(d){const f=document.createElement("h1");f.id="exportToVideoMessage";f.textContent=d.message;document.body.prepend(f);document.body.classList.add("exportingToVideo");this.s.G.style.display="";this.s.Te()}Hf(d){this.Rd=d.message;-1===this.Sc&&(this.Sc=setTimeout(()=>this.mf(),250))}mf(){this.Sc=-1;const d=document.getElementById("exportToVideoMessage");d&&(d.textContent=this.Rd)}If(d){window.gh({type:"exported-video",
blob:d.blob,time:d.time})}})}"use strict";async function P(h){if(h.Ig)throw Error("already initialised");h.Ig=!0;var a=h.dc.Bc("dispatchworker.js");h.Rc=await h.dc.lc(a,h.F,{name:"DispatchWorker"});a=new MessageChannel;h.Wc=a.port1;h.Rc.postMessage({type:"_init","in-port":a.port2},[a.port2]);h.bd=await R(h)}function Q(h){return[h.Wc,h.bd]}
async function R(h){const a=h.Xd.length;var b=h.dc.Bc("jobworker.js");b=await h.dc.lc(b,h.F,{name:"JobWorker"+a});const e=new MessageChannel,g=new MessageChannel;h.Rc.postMessage({type:"_addJobWorker",port:e.port1},[e.port1]);b.postMessage({type:"init",number:a,"dispatch-port":e.port2,"output-port":g.port2},[e.port2,g.port2]);h.Xd.push(b);return g.port1}
self.Me=class{constructor(h){this.dc=h;this.F=h.F;this.F="preview"===h.v?this.F+"workers/":this.F+h.ec;this.Lg=Math.min(navigator.hardwareConcurrency||2,16);this.Rc=null;this.Xd=[];this.bd=this.Wc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Bb({$g:!0,ah:"workermain.js",Qa:["scripts/c3runtime.js"],ic:[],fd:"",Xg:"scripts/",hd:[],ke:"html5"}));"use strict";
async function S(h,a){a=a.type;let b=!0;0===a?b=await T():1===a&&(b=await U());z(h,"permission-result",{type:a,result:b})}async function T(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(h){return console.warn("[Touch] Failed to request orientation permission: ",h),!1}}
async function U(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(h){return console.warn("[Touch] Failed to request motion permission: ",h),!1}}self.Bb.jc(class extends self.wb{constructor(h){super(h,"touch");J(this,"request-permission",a=>S(this,a))}});"use strict";
{const h=180/Math.PI;self.da=class extends self.wb{constructor(a){super(a,"audio");this.Ob=this.c=null;this.Qb=this.Vc=!1;this.sa=()=>this.Eg();this.$=[];this.D=[];this.ha=null;this.Yd="";this.Zd=-1;this.ob=new Map;this.Zc=1;this.pa=!1;this.ed=0;this.fc=1;this.Tc=0;this.be="HRTF";this.Qd="inverse";this.ce=600;this.ae=1E4;this.ee=1;this.Td=this.cd=!1;this.he=this.s.Ke();this.aa=new Map;this.Fa=new Set;this.Xc=!1;this.$c="";this.ya=null;self.C3Audio_OnMicrophoneStream=(b,e)=>this.Pf(b,e);this.Nb=null;
self.C3Audio_GetOutputStream=()=>this.Jf();self.C3Audio_DOMInterface=this;L(this,[["create-audio-context",b=>this.gf(b)],["play",b=>this.cg(b)],["stop",b=>this.Bg(b)],["stop-all",()=>this.Cg()],["set-paused",b=>this.ug(b)],["set-volume",b=>this.zg(b)],["fade-volume",b=>this.nf(b)],["set-master-volume",b=>this.sg(b)],["set-muted",b=>this.tg(b)],["set-silent",b=>this.wg(b)],["set-looping",b=>this.rg(b)],["set-playback-rate",b=>this.vg(b)],["seek",b=>this.jg(b)],["preload",b=>this.dg(b)],["unload",b=>
this.Fg(b)],["unload-all",()=>this.Gg()],["set-suspended",b=>this.xg(b)],["get-suspended",()=>this.sf()],["add-effect",b=>this.xd(b)],["set-effect-param",b=>this.ng(b)],["remove-effects",b=>this.fg(b)],["tick",b=>this.Yf(b)],["load-state",b=>this.Nf(b)]])}async gf(a){a.isiOSCordova&&(this.cd=!0);this.ed=a.timeScaleMode;this.be=["equalpower","HRTF","soundfield"][a.panningModel];this.Qd=["linear","inverse","exponential"][a.distanceModel];this.ce=a.refDistance;this.ae=a.maxDistance;this.ee=a.rolloffFactor;
var b={latencyHint:a.latencyHint};this.he||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.c=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.c=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.yd();this.c.onstatechange=()=>{"running"!==this.c.state&&this.yd()};this.Ob=this.c.createGain();this.Ob.connect(this.c.destination);b=a.listenerPos;this.c.listener.setPosition(b[0],b[1],b[2]);this.c.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=
()=>this.mc();try{await Promise.all(a.preloadList.map(e=>this.Fb(e.originalUrl,e.url,e.type,!1)))}catch(e){console.error("[Construct 3] Preloading sounds failed: ",e)}return{sampleRate:this.c.sampleRate}}yd(){this.Qb||(this.Vc=!1,window.addEventListener("pointerup",this.sa,!0),window.addEventListener("touchend",this.sa,!0),window.addEventListener("click",this.sa,!0),window.addEventListener("keydown",this.sa,!0),this.Qb=!0)}jf(){this.Qb&&(this.Vc=!0,window.removeEventListener("pointerup",this.sa,!0),
window.removeEventListener("touchend",this.sa,!0),window.removeEventListener("click",this.sa,!0),window.removeEventListener("keydown",this.sa,!0),this.Qb=!1)}Eg(){if(!this.Vc){var a=this.c;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),e=a.createBufferSource();e.buffer=b;e.connect(a.destination);e.start(0);"running"===a.state&&this.jf()}}W(){return this.c}mc(){return this.c.currentTime}ta(){return this.Ob}od(a){return(a=this.aa.get(a.toLowerCase()))?a[0].P():this.ta()}le(a,
b){a=a.toLowerCase();let e=this.aa.get(a);e||(e=[],this.aa.set(a,e));b.qg(e.length);b.yg(a);e.push(b);this.Id(a)}Id(a){let b=this.ta();const e=this.aa.get(a);if(e&&e.length){b=e[0].P();for(let g=0,n=e.length;g<n;++g){const q=e[g];g+1===n?q.S(this.ta()):q.S(e[g+1].P())}}for(const g of this.ma(a))g.Re(b);this.ya&&this.$c===a&&(this.ya.disconnect(),this.ya.connect(b))}yb(){return this.Zc}zb(){return this.pa}pg(){this.Td=!0}De(a,b){return b?this.s.Hg(a).then(e=>{const g=this.c.createBuffer(1,e.length,
48E3);g.getChannelData(0).set(e);return g}):new Promise((e,g)=>{this.c.decodeAudioData(a,e,g)})}va(a){this.s.va(a)}Ba(a){this.s.Ba(a)}td(a){let b=0;for(let e=0,g=this.D.length;e<g;++e){const n=this.D[e];this.D[b]=n;n.L===a?n.f():++b}this.D.length=b}Se(){let a=0;for(let b=0,e=this.$.length;b<e;++b){const g=this.$[b];this.$[a]=g;g.ua()?g.f():++a}this.$.length=a}*ma(a){if(a)for(const b of this.D)self.da.Ee(b.Y,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Fb(a,b,e,g,n){for(const q of this.$)if(q.Sa()===
b)return await V(q),q;if(n)return null;g&&(this.cd||this.Td)&&this.Se();n="audio/webm; codecs=opus"===e&&!this.he;g&&n&&this.pg();a=!g||this.cd||n?new self.ze(this,a,b,e,g,n):new self.xe(this,a,b,e,g);this.$.push(a);await V(a);return a}async Ac(a,b,e,g,n){for(const q of this.D)if(q.Sa()===b&&(q.kc()||n))return q.Ve(g),q;a=await this.Fb(a,b,e,n);g="html5"===a.Nc?new self.ye(a.i,a,g):new self.Ae(a.i,a,g);this.D.push(g);return g}Ze(a){let b=this.ob.get(a);if(!b){let e=null;b={gd:0,Wg:new Promise(g=>
e=g),resolve:e};this.ob.set(a,b)}b.gd++}gg(a){const b=this.ob.get(a);if(!b)throw Error("expected pending tag");b.gd--;0===b.gd&&(b.resolve(),this.ob.delete(a))}xc(a){a||(a=this.Yd);return(a=this.ob.get(a))?a.Wg:Promise.resolve()}Gb(){if(0<this.Fa.size)M(this);else for(const a of this.D)if(a.pd()){M(this);break}}Ca(){for(var a of this.Fa)a.Ca();a=this.mc();for(var b of this.D)b.Ca(a);b=this.D.filter(e=>e.pd()).map(e=>e.Ra());z(this,"state",{tickCount:this.Zd,audioInstances:b,analysers:[...this.Fa].map(e=>
e.Ge())});0===b.length&&0===this.Fa.size&&this.Rb&&(this.s.hg(this.ie),this.Rb=!1)}tc(a,b,e){z(this,"trigger",{type:a,tag:b,aiid:e})}async cg(a){const b=a.originalUrl,e=a.url,g=a.type,n=a.isMusic,q=a.tag,v=a.isLooping,B=a.vol,D=a.pos,w=a.panning;let x=a.off;0<x&&!a.trueClock&&(this.c.getOutputTimestamp?(a=this.c.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+this.c.currentTime);this.Yd=q;this.Ze(q);try{this.ha=await this.Ac(b,e,g,q,n),w?(this.ha.Cb(!0),this.ha.Ue(w.x,
w.y,w.angle,w.innerAngle,w.outerAngle,w.outerGain),w.hasOwnProperty("uid")&&this.ha.We(w.uid)):this.ha.Cb(!1),this.ha.Play(v,B,D,x)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.gg(q)}M(this)}Bg(a){a=a.tag;for(const b of this.ma(a))b.na()}Cg(){for(const a of this.D)a.na()}ug(a){const b=a.tag;a=a.paused;for(const e of this.ma(b))a?e.Ua():e.Ab();this.Gb()}zg(a){const b=a.tag;a=a.vol;for(const e of this.ma(b))e.Eb(a)}async nf(a){const b=a.tag,e=a.vol,
g=a.duration;a=a.stopOnEnd;await this.xc(b);for(const n of this.ma(b))n.Fe(e,g,a);this.Gb()}sg(a){this.Zc=a.vol;for(const b of this.D)b.Lb()}tg(a){const b=a.tag;a=a.isMuted;for(const e of this.ma(b))e.ud(a)}wg(a){this.pa=a.isSilent;this.s.Db(this.pa);for(const b of this.D)b.Kb()}rg(a){const b=a.tag;a=a.isLooping;for(const e of this.ma(b))e.vc(a)}async vg(a){const b=a.tag;a=a.rate;await this.xc(b);for(const e of this.ma(b))e.wd(a)}async jg(a){const b=a.tag;a=a.pos;await this.xc(b);for(const e of this.ma(b))e.uc(a)}async dg(a){const b=
a.originalUrl,e=a.url,g=a.type;a=a.isMusic;try{await this.Ac(b,e,g,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async Fg(a){if(a=await this.Fb("",a.url,a.type,a.isMusic,!0))a.f(),a=this.$.indexOf(a),-1!==a&&this.$.splice(a,1)}Gg(){for(const a of this.$)a.f();this.$.length=0}xg(a){a=a.isSuspended;!a&&this.c.resume&&this.c.resume();for(const b of this.D)b.wc(a);a&&this.c.suspend&&this.c.suspend()}sf(){return this.c?this.c.state:"suspended"}Yf(a){this.fc=a.timeScale;this.Tc=
a.gameTime;this.Zd=a.tickCount;if(0!==this.ed)for(var b of this.D)b.Ea();(b=a.listenerPos)&&this.c.listener.setPosition(b[0],b[1],b[2]);for(const e of a.instPans){a=e.uid;for(const g of this.D)g.ga===a&&g.vd(e.x,e.y,e.angle)}}async xd(a){var b=a.type;const e=a.tag;var g=a.params;if("filter"===b)g=new self.re(this,...g);else if("delay"===b)g=new self.pe(this,...g);else if("convolution"===b){b=null;try{b=await this.Fb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",
n);return}g=new self.oe(this,b.Z,...g);g.lg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.se(this,...g);else if("phaser"===b)g=new self.ue(this,...g);else if("gain"===b)g=new self.te(this,...g);else if("tremolo"===b)g=new self.we(this,...g);else if("ringmod"===b)g=new self.ve(this,...g);else if("distortion"===b)g=new self.qe(this,...g);else if("compressor"===b)g=new self.ne(this,...g);else if("analyser"===b)g=new self.me(this,...g);else throw Error("invalid effect type");this.le(e,
g);this.Hd()}ng(a){const b=a.index,e=a.param,g=a.value,n=a.ramp,q=a.time;a=this.aa.get(a.tag);!a||0>b||b>=a.length||(a[b].X(e,g,n,q),this.Hd())}fg(a){a=a.tag.toLowerCase();const b=this.aa.get(a);if(b&&b.length){for(const e of b)e.f();this.aa.delete(a);this.Id(a)}}Ye(a){this.Fa.add(a);this.Gb()}eg(a){this.Fa.delete(a)}Hd(){this.Xc||(this.Xc=!0,Promise.resolve().then(()=>this.kf()))}kf(){const a={};for(const [b,e]of this.aa)a[b]=e.map(g=>g.Ra());z(this,"fxstate",{fxstate:a});this.Xc=!1}async Nf(a){const b=
a.saveLoadMode;if(3!==b)for(var e of this.D)e.ua()&&1===b||(e.ua()||2!==b)&&e.na();for(const g of this.aa.values())for(const n of g)n.f();this.aa.clear();this.fc=a.timeScale;this.Tc=a.gameTime;e=a.listenerPos;this.c.listener.setPosition(e[0],e[1],e[2]);this.pa=a.isSilent;this.s.Db(this.pa);this.Zc=a.masterVolume;e=[];for(const g of Object.values(a.effects))e.push(Promise.all(g.map(n=>this.xd(n))));await Promise.all(e);await Promise.all(a.playing.map(g=>this.wf(g,b)));this.Gb()}async wf(a,b){if(3!==
b){var e=a.bufferOriginalUrl,g=a.bufferUrl,n=a.bufferType,q=a.isMusic,v=a.tag,B=a.isLooping,D=a.volume,w=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.Ac(e,g,n,v,q)}catch(x){console.error("[Construct 3] Audio: error loading audio state: ",x);return}b.Pe(a.pan);b.Play(B,D,w,0);a.isPlaying||b.Ua();b.Ec(a)}}}Pf(a,b){this.ya&&this.ya.disconnect();this.$c=b.toLowerCase();this.ya=this.c.createMediaStreamSource(a);this.ya.connect(this.od(this.$c))}Jf(){this.Nb||(this.Nb=this.c.createMediaStreamDestination(),
this.Ob.connect(this.Nb));return this.Nb.stream}static Ee(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Xe(a){return a*h}static Ce(a){return Math.pow(10,a/20)}static nd(a){return Math.max(Math.min(self.da.Ce(a),1),0)}static Oe(a){return Math.log(a)/Math.log(10)*20}static Ne(a){return self.da.Oe(Math.max(Math.min(a,1),0))}static Rg(a,b){return 1-Math.exp(-b*a)}};self.Bb.jc(self.da)}"use strict";function V(h){h.Ub||(h.Ub=h.Dc());return h.Ub}
self.kd=class{constructor(h,a,b,e,g){this.i=h;this.Ng=a;this.za=b;this.R=e;this.Kg=g;this.Nc="";this.Ub=null}f(){this.Ub=this.i=null}Dc(){}W(){return this.i.W()}oc(){return this.Ng}Sa(){return this.za}nc(){return this.R}ua(){return this.Kg}ea(){}};"use strict";
self.xe=class extends self.kd{constructor(h,a,b,e,g){super(h,a,b,e,g);this.Nc="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.ib=this.jb=null;this.K.addEventListener("canplaythrough",()=>!0);this.nb=this.W().createGain();this.lb=null;this.K.addEventListener("canplay",()=>{this.jb&&(this.jb(),this.ib=this.jb=null);!this.lb&&this.K&&(this.lb=this.W().createMediaElementSource(this.K),this.lb.connect(this.nb))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.za}' error: `,n);this.ib&&(this.ib(n),this.ib=this.jb=null)})}f(){this.i.td(this);this.nb.disconnect();this.nb=null;this.lb.disconnect();this.lb=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.f()}Dc(){return new Promise((h,a)=>{this.jb=h;this.ib=a;this.K.src=this.za})}O(){return this.K}ea(){return this.K.duration}};"use strict";
async function W(h){if(h.wa)return h.wa;var a=h.i.s;if("cordova"===a.v&&a.rd(h.za)&&a.fb)h.wa=await a.vb(h.za);else{a=await fetch(h.za);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);h.wa=await a.arrayBuffer()}}async function X(h){if(h.Z)return h.Z;h.Z=await h.i.De(h.wa,h.Mg);h.wa=null}
self.ze=class extends self.kd{constructor(h,a,b,e,g,n){super(h,a,b,e,g);this.Nc="webaudio";this.Z=this.wa=null;this.Mg=!!n}f(){this.i.td(this);this.Z=this.wa=null;super.f()}async Dc(){try{await W(this),await X(this)}catch(h){console.error(`[Construct 3] Failed to load audio '${this.za}': `,h)}}ea(){return this.Z?this.Z.duration:0}};"use strict";
{let h=0;self.ld=class{constructor(a,b,e){this.i=a;this.L=b;this.Y=e;this.Mb=h++;this.M=this.W().createGain();this.M.connect(this.ta());this.B=null;this.gb=!1;this.ka=[0,0,0];this.ja=[0,0,0];this.I=!0;this.V=this.la=this.H=!1;this.sb=1;this.Ga=!1;this.ra=1;a=this.i.ed;this.Yc=1===a&&!this.ua()||2===a;this.bb=this.ga=-1;this.ge=!1}f(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ta(){return this.i.od(this.Y)}yb(){return this.i.yb()}xb(){return this.Yc?
this.i.Tc:performance.now()/1E3}oc(){return this.L.oc()}Sa(){return this.L.Sa()}nc(){return this.L.nc()}ua(){return this.L.ua()}Ve(a){this.Y=a}T(){}kc(){}IsPlaying(){return!this.I&&!this.H&&!this.T()}pd(){return!this.I&&!this.T()}Aa(){}ea(){return this.L.ea()}Play(){}na(){}Ua(){}Ab(){}Eb(a){this.sb=a;this.M.gain.cancelScheduledValues(0);this.bb=-1;this.M.gain.value=this.pc()}Fe(a,b,e){if(!this.Ga){a*=this.yb();var g=this.M.gain;g.cancelScheduledValues(0);var n=this.i.mc();b=n+b;g.setValueAtTime(g.value,
n);g.linearRampToValueAtTime(a,b);this.sb=a;this.bb=b;this.ge=e}}Lb(){this.Eb(this.sb)}Ca(a){-1!==this.bb&&a>=this.bb&&(this.bb=-1,this.ge&&this.na(),this.i.tc("fade-ended",this.Y,this.Mb))}pc(){const a=this.sb*this.yb();return isFinite(a)?a:0}ud(a){a=!!a;this.Ga!==a&&(this.Ga=a,this.Kb())}zb(){return this.i.zb()}Kb(){}vc(){}wd(a){this.ra!==a&&(this.ra=a,this.Ea())}Ea(){}uc(){}wc(){}Cb(a){a=!!a;this.gb!==a&&((this.gb=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.be,this.B.distanceModel=
this.i.Qd,this.B.refDistance=this.i.ce,this.B.maxDistance=this.i.ae,this.B.rolloffFactor=this.i.ee),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ta())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ta())))}Ue(a,b,e,g,n,q){this.gb&&(this.vd(a,b,e),a=self.da.Xe,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(n),this.B.coneOuterGain=q)}vd(a,b,e){this.gb&&(this.ka[0]=a,this.ka[1]=b,this.ka[2]=0,this.ja[0]=Math.cos(e),this.ja[1]=Math.sin(e),this.ja[2]=0,this.B.setPosition(...this.ka),
this.B.setOrientation(...this.ja))}We(a){this.ga=a}qc(){}Re(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ra(){return{aiid:this.Mb,tag:this.Y,duration:this.ea(),volume:this.sb,isPlaying:this.IsPlaying(),playbackTime:this.Aa(),playbackRate:this.ra,uid:this.ga,bufferOriginalUrl:this.oc(),bufferUrl:"",bufferType:this.nc(),isMusic:this.ua(),isLooping:this.V,isMuted:this.Ga,resumePosition:this.qc(),pan:this.He()}}Ec(a){this.wd(a.playbackRate);this.ud(a.isMuted)}He(){if(!this.B)return null;const a=
this.B;return{pos:this.ka,orient:this.ja,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}Pe(a){if(a){this.Cb(!0);a=this.B;var b=a.pos;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];b=a.orient;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];a.setPosition(...this.ka);a.setOrientation(...this.ja);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ga=a.uid}else this.Cb(!1)}}}"use strict";
self.ye=class extends self.ld{constructor(h,a,b){super(h,a,b);this.L.nb.connect(this.M);this.L.onended=()=>this.Gc()}f(){this.na();this.L.nb.disconnect();super.f()}O(){return this.L.O()}Gc(){this.I=!0;this.ga=-1;this.i.tc("ended",this.Y,this.Mb)}T(){return this.O().ended}kc(){return this.I?!0:this.T()}Aa(){let h=this.O().currentTime;this.V||(h=Math.min(h,this.ea()));return h}Play(h,a,b){const e=this.O();1!==e.playbackRate&&(e.playbackRate=1);e.loop!==h&&(e.loop=h);this.Eb(a);e.muted&&(e.muted=!1);
if(e.currentTime!==b)try{e.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Sa()}' to position '${b}': `,g)}this.i.va(e);this.H=this.I=!1;this.V=h;this.ra=1}na(){const h=this.O();h.paused||h.pause();this.i.Ba(h);this.I=!0;this.H=!1;this.ga=-1}Ua(){if(!(this.H||this.I||this.T())){var h=this.O();h.paused||h.pause();this.i.Ba(h);this.H=!0}}Ab(){!this.H||this.I||this.T()||(this.i.va(this.O()),this.H=!1)}Kb(){this.O().muted=this.Ga||this.zb()}vc(h){h=!!h;this.V!==h&&
(this.V=h,this.O().loop=h)}Ea(){let h=this.ra;this.Yc&&(h*=this.i.fc);try{this.O().playbackRate=h}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${h}':`,a)}}uc(h){if(!this.I&&!this.T())try{this.O().currentTime=h}catch(a){console.warn(`[Construct 3] Error seeking audio to '${h}': `,a)}}qc(){return this.Aa()}wc(h){h?this.IsPlaying()?(this.O().pause(),this.la=!0):this.la=!1:this.la&&(this.i.va(this.O()),this.la=!1)}};"use strict";
function Y(h){h.j&&h.j.disconnect();h.j=null;h.Ya=null}
self.Ae=class extends self.ld{constructor(h,a,b){super(h,a,b);this.j=null;this.Xb=e=>this.Gc(e);this.Uc=!0;this.Ya=null;this.N=this.Yb=this.Zb=0;this.ad=1}f(){this.na();Y(this);this.Xb=null;super.f()}Gc(h){this.H||this.la||h.target!==this.Ya||(this.I=this.Uc=!0,this.ga=-1,Y(this),this.i.tc("ended",this.Y,this.Mb))}T(){return!this.I&&this.j&&this.j.loop||this.H?!1:this.Uc}kc(){return!this.j||this.I?!0:this.T()}Aa(){let h;h=this.H?this.N:this.Yb+(this.xb()-this.Zb)*this.ra;this.V||(h=Math.min(h,this.ea()));
return h}Play(h,a,b,e){this.ad=1;this.Eb(a);Y(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.Z;this.j.connect(this.M);this.Ya=this.j;this.j.onended=this.Xb;this.j.loop=h;this.j.start(e,b);this.H=this.I=this.Uc=!1;this.V=h;this.ra=1;this.Zb=this.xb();this.Yb=b}na(){if(this.j)try{this.j.stop(0)}catch(h){}this.I=!0;this.H=!1;this.ga=-1}Ua(){this.H||this.I||this.T()||(this.N=this.Aa(),this.V&&(this.N%=this.ea()),this.H=!0,this.j.stop(0))}Ab(){!this.H||this.I||this.T()||(Y(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.Z,this.j.connect(this.M),this.Ya=this.j,this.j.onended=this.Xb,this.j.loop=this.V,this.Lb(),this.Ea(),this.j.start(0,this.N),this.Zb=this.xb(),this.Yb=this.N,this.H=!1)}pc(){return super.pc()*this.ad}Kb(){this.ad=this.Ga||this.zb()?0:1;this.Lb()}vc(h){h=!!h;this.V!==h&&(this.V=h,this.j&&(this.j.loop=h))}Ea(){let h=this.ra;this.Yc&&(h*=this.i.fc);this.j&&(this.j.playbackRate.value=h)}uc(h){this.I||this.T()||(this.H?this.N=h:(this.Ua(),this.N=h,this.Ab()))}qc(){return this.N}wc(h){h?
this.IsPlaying()?(this.la=!0,this.N=this.Aa(),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.la=!1:this.la&&(Y(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.Z,this.j.connect(this.M),this.Ya=this.j,this.j.onended=this.Xb,this.j.loop=this.V,this.Lb(),this.Ea(),this.j.start(0,this.N),this.Zb=this.xb(),this.Yb=this.N,this.la=!1)}Ec(h){super.Ec(h);this.N=h.resumePosition}};"use strict";
{class h{constructor(a){this.i=a;this.c=a.W();this.Ud=-1;this.R=this.Y="";this.g=null}f(){this.c=null}qg(a){this.Ud=a}yg(a){this.Y=a}o(){return this.c.createGain()}P(){}S(){}m(a,b,e,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var n=this.c.currentTime;g+=n;switch(e){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,g)}}}Ra(){return{type:this.R,tag:this.Y,params:this.g}}}
self.re=class extends h{constructor(a,b,e,g,n,q,v){super(a);this.R="filter";this.g=[b,e,g,n,q,v];this.l=this.o();this.b=this.o();this.b.gain.value=v;this.a=this.o();this.a.gain.value=1-v;this.A=this.c.createBiquadFilter();this.A.type=b;this.A.frequency.value=e;this.A.detune.value=g;this.A.Q.value=n;this.A.gain.vlaue=q;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b)}f(){this.l.disconnect();this.A.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,e,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,e,g);this.m(this.a.gain,1-b,e,g);break;case 1:this.g[1]=b;this.m(this.A.frequency,b,e,g);break;case 2:this.g[2]=b;this.m(this.A.detune,b,e,g);break;case 3:this.g[3]=b;this.m(this.A.Q,b,e,g);break;case 4:this.g[4]=b,this.m(this.A.gain,b,e,g)}}};self.pe=class extends h{constructor(a,b,e,g){super(a);this.R="delay";this.g=[b,e,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.kb=this.o();this.U=this.c.createDelay(b);this.U.delayTime.value=b;this.ab=this.o();this.ab.gain.value=e;this.l.connect(this.kb);this.l.connect(this.a);this.kb.connect(this.b);this.kb.connect(this.U);this.U.connect(this.ab);this.ab.connect(this.kb)}f(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.kb.disconnect();this.U.disconnect();this.ab.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,e,g){const n=self.da.nd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,e,g);this.m(this.a.gain,1-b,e,g);break;case 4:this.g[1]=n(b);this.m(this.ab.gain,n(b),e,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,e,g)}}};self.oe=class extends h{constructor(a,b,e,g){super(a);this.R="convolution";this.g=[e,g];this.Od=this.Nd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.$a=this.c.createConvolver();this.$a.normalize=e;this.$a.buffer=b;this.l.connect(this.$a);this.l.connect(this.a);this.$a.connect(this.b)}f(){this.l.disconnect();this.$a.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,e,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,e,g),this.m(this.a.gain,1-b,e,g)}}lg(a,b){this.Nd=a;this.Od=b}Ra(){const a=
super.Ra();a.bufferOriginalUrl=this.Nd;a.bufferUrl="";a.bufferType=this.Od;return a}};self.se=class extends h{constructor(a,b,e,g,n,q){super(a);this.R="flanger";this.g=[b,e,g,n,q];this.l=this.o();this.a=this.o();this.a.gain.value=1-q/2;this.b=this.o();this.b.gain.value=q/2;this.cb=this.o();this.cb.gain.value=n;this.U=this.c.createDelay(b+e);this.U.delayTime.value=b;this.u=this.c.createOscillator();this.u.frequency.value=g;this.J=this.o();this.J.gain.value=e;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.cb);this.cb.connect(this.U);this.u.connect(this.J);this.J.connect(this.U.delayTime);this.u.start(0)}f(){this.u.stop(0);this.l.disconnect();this.U.disconnect();this.u.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();this.cb.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,e,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,e,g);this.m(this.a.gain,1-b/2,e,g);break;case 6:this.g[1]=b/1E3;this.m(this.J.gain,b/1E3,e,g);break;case 7:this.g[2]=b;this.m(this.u.frequency,b,e,g);break;case 8:this.g[3]=b/100,this.m(this.cb.gain,b/100,e,g)}}};self.ue=class extends h{constructor(a,b,e,g,n,q,v){super(a);this.R="phaser";this.g=[b,e,g,n,q,v];this.l=this.o();this.a=this.o();this.a.gain.value=1-v/2;this.b=this.o();this.b.gain.value=v/2;this.A=this.c.createBiquadFilter();this.A.type="allpass";this.A.frequency.value=b;this.A.detune.value=
e;this.A.Q.value=g;this.u=this.c.createOscillator();this.u.frequency.value=q;this.J=this.o();this.J.gain.value=n;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b);this.u.connect(this.J);this.J.connect(this.A.frequency);this.u.start(0)}f(){this.u.stop(0);this.l.disconnect();this.A.disconnect();this.u.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,e,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,e,g);this.m(this.a.gain,1-b/2,e,g);break;case 1:this.g[0]=b;this.m(this.A.frequency,b,e,g);break;case 2:this.g[1]=b;this.m(this.A.detune,b,e,g);break;case 3:this.g[2]=b;this.m(this.A.Q,b,e,g);break;case 6:this.g[3]=b;this.m(this.J.gain,b,e,g);break;case 7:this.g[4]=b,this.m(this.u.frequency,b,e,g)}}};self.te=class extends h{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}f(){this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,e,g){const n=self.da.nd;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),e,g)}}};self.we=class extends h{constructor(a,b,e){super(a);this.R="tremolo";this.g=[b,e];this.h=this.o();this.h.gain.value=1-e/2;this.u=this.c.createOscillator();this.u.frequency.value=b;this.J=this.o();this.J.gain.value=e/2;this.u.connect(this.J);this.J.connect(this.h.gain);this.u.start(0)}f(){this.u.stop(0);this.u.disconnect();
this.J.disconnect();this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,e,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,e,g);this.m(this.J.gain,b/2,e,g);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,e,g)}}};self.ve=class extends h{constructor(a,b,e){super(a);this.R="ringmod";this.g=[b,e];this.l=this.o();this.b=this.o();this.b.gain.value=e;this.a=this.o();this.a.gain.value=1-e;this.qb=this.o();this.qb.gain.value=
0;this.u=this.c.createOscillator();this.u.frequency.value=b;this.u.connect(this.qb.gain);this.u.start(0);this.l.connect(this.qb);this.l.connect(this.a);this.qb.connect(this.b)}f(){this.u.stop(0);this.u.disconnect();this.qb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,e,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,e,g);
this.m(this.a.gain,1-b,e,g);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,e,g)}}};self.qe=class extends h{constructor(a,b,e,g,n,q){super(a);this.R="distortion";this.g=[b,e,g,n,q];this.l=this.o();this.cc=this.o();this.bc=this.o();this.mg(g,n);this.b=this.o();this.b.gain.value=q;this.a=this.o();this.a.gain.value=1-q;this.hc=this.c.createWaveShaper();this.Qc=new Float32Array(65536);this.qf(b,e);this.hc.curve=this.Qc;this.l.connect(this.cc);this.l.connect(this.a);this.cc.connect(this.hc);this.hc.connect(this.bc);
this.bc.connect(this.b)}f(){this.l.disconnect();this.cc.disconnect();this.hc.disconnect();this.bc.disconnect();this.b.disconnect();this.a.disconnect();super.f()}mg(a,b){.01>a&&(a=.01);this.cc.gain.value=a;this.bc.gain.value=Math.pow(1/a,.6)*b}qf(a,b){for(let e=0;32768>e;++e){let g=e/32768;g=this.Ag(g,a,b);this.Qc[32768+e]=g;this.Qc[32768-e-1]=-g}}Ag(a,b,e){e=1.05*e*b-b;const g=0>a?-a:a;return(g<b?g:b+e*self.da.Rg(g-b,1/e))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,e,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,e,g),this.m(this.a.gain,1-b,e,g)}}};self.ne=class extends h{constructor(a,b,e,g,n,q){super(a);this.R="compressor";this.g=[b,e,g,n,q];this.h=this.c.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=e;this.h.ratio.value=g;this.h.attack.value=n;this.h.release.value=q}f(){this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.me=class extends h{constructor(a,b,e){super(a);this.R="analyser";this.g=[b,e];this.h=this.c.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=e;this.Sd=new Float32Array(this.h.frequencyBinCount);this.fe=new Uint8Array(b);this.de=this.Ka=0;this.i.Ye(this)}f(){this.i.eg(this);this.h.disconnect();super.f()}Ca(){this.h.getFloatFrequencyData(this.Sd);this.h.getByteTimeDomainData(this.fe);const a=this.h.fftSize;let b=this.Ka=0;for(var e=0;e<a;++e){let g=(this.fe[e]-128)/128;0>g&&(g=-g);
this.Ka<g&&(this.Ka=g);b+=g*g}e=self.da.Ne;this.Ka=e(this.Ka);this.de=e(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Ge(){return{tag:this.Y,index:this.Ud,peak:this.Ka,rms:this.de,binCount:this.h.frequencyBinCount,freqBins:this.Sd}}}};
